FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /app

EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000;
ENV ASPNETCORE_ENVIRONMENT=Development

COPY . .
RUN dotnet restore
RUN dotnet publish -o /app/published-app

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /app
COPY --from=build /app/published-app /app
ENTRYPOINT [ "dotnet", "/app/API.dll" ,"--server.urls", "http://+:5000"]
